config/routes.rb
Rails.application.routes.draw do
  resources :movies

  resources :reviews

  devise_for :users, skip: [:sessions, :registrations]

  root 'movies#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  has_many :movies
  has_many :reviews
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :user_id, :user_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment, :user_id, :movie_id, :movie_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :movie_length, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :movie_length, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :director, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :director, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rating, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :rating, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :user_id, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  movies_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/movies/edit.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Movie %></h1>
</div>
<%= render :partial => 'form' %>

app/views/movies/index.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => Movie %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:movie_length) %></th>
      <th><%= model_class.human_attribute_name(:director) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.id %></td>
        <td><%= movie.title %></td>
        <td><%= movie.description %></td>
        <td><%= movie.movie_length %></td>
        <td><%= movie.director %></td>
        <td><%= movie.rating %></td>
        <td><%= movie.user_id %></td>
        <td><%=l movie.created_at, format: :long %></td>
        <td>
          <%= link_to movie_path(movie), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to movie_path(movie), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_movie_path,
            :class => 'btn btn-primary' %>

app/views/movies/new.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Movie %></h1>
</div>
<%= render :partial => 'form' %>

app/views/movies/show.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => Movie %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @movie.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @movie.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:movie_length) %></dt>
      <dd><pre class="prettyprint"><%= @movie.movie_length %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:director) %></dt>
      <dd><pre class="prettyprint"><%= @movie.director %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:rating) %></dt>
      <dd><pre class="prettyprint"><%= @movie.rating %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:user_id) %></dt>
      <dd><pre class="prettyprint"><%= @movie.user_id %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              movies_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_movie_path(@movie), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              movie_path(@movie),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/reviews/_form.html.erb
<%= form_for @review, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :rating, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :rating, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :comment, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :comment, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :user_id, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :movie_id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :movie_id, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  reviews_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Review %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reviews/index.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => Review %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:movie_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.id %></td>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= review.user_id %></td>
        <td><%= review.movie_id %></td>
        <td><%=l review.created_at, format: :long %></td>
        <td>
          <%= link_to review_path(review), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to review_path(review), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_review_path,
            :class => 'btn btn-primary' %>

app/views/reviews/new.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Review %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reviews/show.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => Review %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:rating) %></dt>
      <dd><pre class="prettyprint"><%= @review.rating %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:comment) %></dt>
      <dd><pre class="prettyprint"><%= @review.comment %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:user_id) %></dt>
      <dd><pre class="prettyprint"><%= @review.user_id %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:movie_id) %></dt>
      <dd><pre class="prettyprint"><%= @review.movie_id %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              reviews_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_review_path(@review), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              review_path(@review),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>